export const testData = [
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Dock 16 / 50 Wallgrove Road  E",
        addressLine2: "",
        addressLine3: "",
        locality: "EASTERN CREEK",
        postCode: "2766",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "16/50 WALLGROVE ROAD",
        locality: "EASTERN CREEK",
        state: "NSW",
        postCode: "2766",
        country: "Australia",
        longitude: 150.8519974,
        latitude: -33.8047049,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "199B/109-113 George St Pa",
        addressLine2: "",
        addressLine3: "",
        locality: "PARRAMATTA",
        postCode: "2150",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "199B",
        streetAddress: "199B/109-113 GEORGE STREET",
        locality: "PARRAMATTA",
        state: "NSW",
        postCode: "2150",
        country: "Australia",
        longitude: 151.01017691,
        latitude: -33.81567868,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Unit B609 444 Harris Street",
        addressLine2: "",
        addressLine3: "",
        locality: "ULTIMO",
        postCode: "2007",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "B609",
        streetAddress: "B609/444 HARRIS STREET",
        locality: "ULTIMO",
        state: "NSW",
        postCode: "2007",
        country: "Australia",
        longitude: 151.19834488,
        latitude: -33.87679092,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "WORKSHOP 7  BUILDING 7  UC  11",
        addressLine2: "",
        addressLine3: "",
        locality: "BRUCE ACT",
        postCode: "2617",
        state: "ACT",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "7/",
        locality: "BRUCE",
        state: "ACT",
        postCode: "2617",
        country: "Australia",
        longitude: 149.0833844,
        latitude: -35.2365396,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "36 Sherwood Place",
        addressLine2: "",
        addressLine3: "",
        locality: "NORTH RYDE",
        postCode: "2113",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "36 SHERWOOD PLACE",
        locality: "NORTH RYDE",
        state: "NSW",
        postCode: "2113",
        country: "Australia",
        longitude: 151.12873566,
        latitude: -33.80495036,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "89 Addison Road",
        addressLine2: "",
        addressLine3: "",
        locality: "MARRICKVILLE",
        postCode: "2204",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "89 ADDISON ROAD",
        locality: "MARRICKVILLE",
        state: "NSW",
        postCode: "2204",
        country: "Australia",
        longitude: 151.16479985,
        latitude: -33.90251117,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "1C Marshall Street",
        addressLine2: "",
        addressLine3: "",
        locality: "PETERSHAM",
        postCode: "2049",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "1C MARSHALL STREET",
        locality: "PETERSHAM",
        state: "NSW",
        postCode: "2049",
        country: "Australia",
        longitude: 151.15992893,
        latitude: -33.89780369,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 278 213 PRINCES HIGHWAY",
        addressLine2: "",
        addressLine3: "",
        locality: "ARNCLIFFE",
        postCode: "2205",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "278",
        streetAddress: "278/213 PRINCES HIGHWAY",
        locality: "ARNCLIFFE",
        state: "NSW",
        postCode: "2205",
        country: "Australia",
        longitude: 151.1456355,
        latitude: -33.94046226,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 43/504-516 CHURCH ST",
        addressLine2: "",
        addressLine3: "",
        locality: "NORTH PARRAMATTA",
        postCode: "2151",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "43",
        streetAddress: "43/504-516 CHURCH STREET",
        locality: "NORTH PARRAMATTA",
        state: "NSW",
        postCode: "2151",
        country: "Australia",
        longitude: 151.00547942,
        latitude: -33.80074152,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Unit 505  53 Kildare Road",
        addressLine2: "",
        addressLine3: "",
        locality: "BLACKTOWN",
        postCode: "2148",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "505",
        streetAddress: "505/53 KILDARE ROAD",
        locality: "BLACKTOWN",
        state: "NSW",
        postCode: "2148",
        country: "Australia",
        longitude: 150.90093,
        latitude: -33.7685158,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "U 8  62-66 Houston Rd",
        addressLine2: "",
        addressLine3: "",
        locality: "KINGSFORD",
        postCode: "2032",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "8",
        streetAddress: "8/62-66 HOUSTON ROAD",
        locality: "KINGSFORD",
        state: "NSW",
        postCode: "2032",
        country: "Australia",
        longitude: 151.22585473,
        latitude: -33.92279738,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Level 3 cafe 500 Harris Street",
        addressLine2: "",
        addressLine3: "",
        locality: "ULTIMO",
        postCode: "2007",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "LEVEL CAFE 500 HARRIS STREET",
        locality: "ULTIMO",
        state: "NSW",
        postCode: "2007",
        country: "Australia",
        longitude: 151.20005531,
        latitude: -33.87860123,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "SHOP 58A LVL 4-5 1 RIDER",
        addressLine2: "",
        addressLine3: "",
        locality: "RHODES",
        postCode: "2138",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "4-5/1 RIDER BOULEVARD",
        locality: "RHODES",
        state: "NSW",
        postCode: "2138",
        country: "Australia",
        longitude: 151.084473,
        latitude: -33.8351248,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "5/63-67 GLADSTONE ST",
        addressLine2: "",
        addressLine3: "",
        locality: "KOGARAH",
        postCode: "2217",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "5",
        streetAddress: "5/63-67 GLADSTONE STREET",
        locality: "KOGARAH",
        state: "NSW",
        postCode: "2217",
        country: "Australia",
        longitude: 151.13659768,
        latitude: -33.96364527,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "APT 801/425 BOURKE STREET",
        addressLine2: "",
        addressLine3: "",
        locality: "SURRY HILLS",
        postCode: "2010",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "801",
        streetAddress: "801/425 BOURKE STREET",
        locality: "SURRY HILLS",
        state: "NSW",
        postCode: "2010",
        country: "Australia",
        longitude: 151.21608376,
        latitude: -33.88273595,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "G01/9 HARRIETTE STREET",
        addressLine2: "",
        addressLine3: "",
        locality: "NEUTRAL BAY",
        postCode: "2089",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "G01/9 HARRIETTE STREET",
        locality: "NEUTRAL BAY",
        state: "NSW",
        postCode: "2089",
        country: "Australia",
        longitude: 151.21933606,
        latitude: -33.8378464,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "BLDNG 1 60 WALLGROVE ROAD",
        addressLine2: "",
        addressLine3: "",
        locality: "MINCHINBURY",
        postCode: "2770",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "1/60 WALLGROVE ROAD",
        locality: "MINCHINBURY",
        state: "NSW",
        postCode: "2770",
        country: "Australia",
        longitude: 150.85097798,
        latitude: -33.79409583,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Unit 28  17-21 Bowden Street",
        addressLine2: "",
        addressLine3: "",
        locality: "ALEXANDRIA",
        postCode: "2015",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "28",
        streetAddress: "28/17-21 BOWDEN STREET",
        locality: "ALEXANDRIA",
        state: "NSW",
        postCode: "2015",
        country: "Australia",
        longitude: 151.19592434,
        latitude: -33.90532172,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Unit 20  30-44 Garden Street",
        addressLine2: "",
        addressLine3: "",
        locality: "ALEXANDRIA",
        postCode: "2015",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "20",
        streetAddress: "20/30-44 GARDEN STREET",
        locality: "ALEXANDRIA",
        state: "NSW",
        postCode: "2015",
        country: "Australia",
        longitude: 151.19750933,
        latitude: -33.89609688,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNITS 4-5  LOT 2 FAIRFIELD ST",
        addressLine2: "",
        addressLine3: "",
        locality: "VILLAWOOD",
        postCode: "2163",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "4-5/4 FAIRFIELD STREET",
        locality: "FAIRFIELD EAST",
        state: "NSW",
        postCode: "2165",
        country: "Australia",
        longitude: 150.9844273,
        latitude: -33.8703455,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Unit 611  84-108 Anzac Parade",
        addressLine2: "",
        addressLine3: "",
        locality: "KENSINGTON",
        postCode: "2033",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "611",
        streetAddress: "611/84-108 ANZAC PARADE",
        locality: "KENSINGTON",
        state: "NSW",
        postCode: "2033",
        country: "Australia",
        longitude: 151.22407493,
        latitude: -33.90662082,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 7  169 ADDERTON ROAD",
        addressLine2: "",
        addressLine3: "",
        locality: "CARLINGFORD",
        postCode: "2118",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "7",
        streetAddress: "7/169 ADDERTON ROAD",
        locality: "CARLINGFORD",
        state: "NSW",
        postCode: "2118",
        country: "Australia",
        longitude: 151.04354221,
        latitude: -33.78589249,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "LEVEL 11  160 SUSSEX STREET",
        addressLine2: "",
        addressLine3: "",
        locality: "SYDNEY",
        postCode: "2000",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "LEVEL 11 160 SUSSEX STREET",
        locality: "SYDNEY",
        state: "NSW",
        postCode: "2000",
        country: "Australia",
        longitude: 151.20400894,
        latitude: -33.86976403,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "Unit 20  20 Oliver Street",
        addressLine2: "",
        addressLine3: "",
        locality: "LYNEHAM",
        postCode: "2602",
        state: "ACT",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "20",
        streetAddress: "20/20 OLIVER STREET",
        locality: "LYNEHAM",
        state: "ACT",
        postCode: "2602",
        country: "Australia",
        longitude: 149.13272041,
        latitude: -35.25001884,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 2 / 162A BURWOOD RD",
        addressLine2: "",
        addressLine3: "",
        locality: "CONCORD",
        postCode: "2137",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "2",
        streetAddress: "2/162A BURWOOD ROAD",
        locality: "CONCORD",
        state: "NSW",
        postCode: "2137",
        country: "Australia",
        longitude: 151.11698439,
        latitude: -33.85834844,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 304/31-35 SMALLWOOD AVE",
        addressLine2: "",
        addressLine3: "",
        locality: "HOMEBUSH",
        postCode: "2140",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "304",
        streetAddress: "304/31-35 SMALLWOOD AVENUE",
        locality: "HOMEBUSH",
        state: "NSW",
        postCode: "2140",
        country: "Australia",
        longitude: 151.07698458,
        latitude: -33.86371237,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "TOWNHOUSE 17/162D BURWOOD ROAD",
        addressLine2: "",
        addressLine3: "",
        locality: "CONCORD",
        postCode: "2137",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "TOWNHOUSE",
        flatNumber: "17",
        streetAddress: "17/162D BURWOOD ROAD",
        locality: "CONCORD",
        state: "NSW",
        postCode: "2137",
        country: "Australia",
        longitude: 151.11719935,
        latitude: -33.85745617,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 13  18-22 BALL AVENUE",
        addressLine2: "",
        addressLine3: "",
        locality: "EASTWOOD",
        postCode: "2122",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "13",
        streetAddress: "13/18-22 BALL AVENUE",
        locality: "EASTWOOD",
        state: "NSW",
        postCode: "2122",
        country: "Australia",
        longitude: 151.08380133,
        latitude: -33.78786584,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "108 THE SANCTUARY DRIVE",
        addressLine2: "",
        addressLine3: "",
        locality: "LEONAY",
        postCode: "2750",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "108 THE SANCTUARY DRIVE",
        locality: "LEONAY",
        state: "NSW",
        postCode: "2750",
        country: "Australia",
        longitude: 150.6432293,
        latitude: -33.7609282,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "51 DEVITT CRESCENT",
        addressLine2: "",
        addressLine3: "",
        locality: "THE OAKS",
        postCode: "2570",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "51 DEVITT CRESCENT",
        locality: "THE OAKS",
        state: "NSW",
        postCode: "2570",
        country: "Australia",
        longitude: 150.56996136,
        latitude: -34.08383795,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 1503/88 CHURCH ST",
        addressLine2: "",
        addressLine3: "",
        locality: "PARRAMATTA",
        postCode: "2150",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "1503",
        streetAddress: "1503/88 CHURCH STREET",
        locality: "PARRAMATTA",
        state: "NSW",
        postCode: "2150",
        country: "Australia",
        longitude: 151.00417373,
        latitude: -33.81943896,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 8  6 GUTHRIE STREET",
        addressLine2: "",
        addressLine3: "",
        locality: "DICKSON",
        postCode: "2602",
        state: "ACT",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "8",
        streetAddress: "8/6 GUTHRIE STREET",
        locality: "DICKSON",
        state: "ACT",
        postCode: "2602",
        country: "Australia",
        longitude: 149.1370289,
        latitude: -35.25422491,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "24-26 EWAN STREET",
        addressLine2: "",
        addressLine3: "",
        locality: "MASCOT",
        postCode: "2020",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "24-26 EWAN STREET",
        locality: "MASCOT",
        state: "NSW",
        postCode: "2020",
        country: "Australia",
        longitude: 151.18472802,
        latitude: -33.92985721,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 28/112 MCMICHAEL TCE",
        addressLine2: "",
        addressLine3: "",
        locality: "DENMAN PROSPECT",
        postCode: "2611",
        state: "ACT",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "28",
        streetAddress: "28/112 MCMICHAEL TERRACE",
        locality: "DENMAN PROSPECT",
        state: "ACT",
        postCode: "2611",
        country: "Australia",
        longitude: 149.02230843,
        latitude: -35.30008301,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "SHOP 95/732 HARRIS ST",
        addressLine2: "",
        addressLine3: "",
        locality: "ULTIMO",
        postCode: "2007",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "SHOP",
        flatNumber: "95",
        streetAddress: "95/732 HARRIS STREET",
        locality: "ULTIMO",
        state: "NSW",
        postCode: "2007",
        country: "Australia",
        longitude: 151.20245376,
        latitude: -33.88346663,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 144/1 ANTHONY ROLFE AVE",
        addressLine2: "",
        addressLine3: "",
        locality: "GUNGAHLIN",
        postCode: "2912",
        state: "ACT",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "144",
        streetAddress: "144/1 ANTHONY ROLFE AVENUE",
        locality: "GUNGAHLIN",
        state: "ACT",
        postCode: "2912",
        country: "Australia",
        longitude: 149.12955266,
        latitude: -35.18222764,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "UNIT 34/37 CAMPBELL ST",
        addressLine2: "",
        addressLine3: "",
        locality: "PARRAMATTA",
        postCode: "2150",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "UNIT",
        flatNumber: "34",
        streetAddress: "34/37 CAMPBELL STREET",
        locality: "PARRAMATTA",
        state: "NSW",
        postCode: "2150",
        country: "Australia",
        longitude: 151.00241912,
        latitude: -33.81910619,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "ZOLL MEDICAL 14/39 HERBERT",
        addressLine2: "",
        addressLine3: "",
        locality: "ST LEONARDS",
        postCode: "2065",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "14/39 HERBERT STREET",
        locality: "ST LEONARDS",
        state: "NSW",
        postCode: "2065",
        country: "Australia",
        longitude: 151.1925637,
        latitude: -33.8158661,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "31A BELLA VISTA DR",
        addressLine2: "",
        addressLine3: "",
        locality: "BELLA VISTA",
        postCode: "2153",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "31A BELLA VISTA DRIVE",
        locality: "BELLA VISTA",
        state: "NSW",
        postCode: "2153",
        country: "Australia",
        longitude: 150.9603343,
        latitude: -33.7417833,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "VILLA 13 19-21 KENNETH AVENUE",
        addressLine2: "",
        addressLine3: "",
        locality: "BAULKHAM HILLS",
        postCode: "2153",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "gnaf",
      validatedAddress: {
        flatType: "VILLA",
        flatNumber: "13",
        streetAddress: "13/19-21 KENNETH AVENUE",
        locality: "BAULKHAM HILLS",
        state: "NSW",
        postCode: "2153",
        country: "Australia",
        longitude: 150.98709553,
        latitude: -33.76027437,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "SHOP 3 ST CLAIR SHOP CENTRE",
        addressLine2: "",
        addressLine3: "",
        locality: "ST CLAIR",
        postCode: "2759",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "3 SAINT CLAIR AVENUE",
        locality: "SAINT CLAIR",
        state: "NSW",
        postCode: "2759",
        country: "Australia",
        longitude: 150.7884679,
        latitude: -33.7906713,
      },
    },
  },
  {
    url: {
      protocol: "http",
      port: "8080",
      path: ["addresses", "validate"],
      host: ["localhost"],
      query: [],
      variable: [],
    },
    method: "POST",
    requestBody: {
      inputAddress: {
        addressLine1: "SHOP 7 CARINGBAH SHOPPING",
        addressLine2: "",
        addressLine3: "",
        locality: "CARINGBAH",
        postCode: "2229",
        state: "NSW",
        country: "Australia",
      },
    },
    responseStatus: 200,
    rawResponse: {
      resolver: "google",
      validatedAddress: {
        flatType: "",
        flatNumber: "",
        streetAddress: "7 CARINGBAH ROAD",
        locality: "WOOLOOWARE",
        state: "NSW",
        postCode: "2230",
        country: "Australia",
        longitude: 151.1356328,
        latitude: -34.0482939,
      },
    },
  },
];
